import React, { RefObject } from 'react';
import { TextInput, StyleProp, TextStyle, ViewStyle } from 'react-native';
import { ActionSheetOptions } from '@expo/react-native-action-sheet';
import { ActionsProps } from '../Actions';
import { AvatarProps } from '../Avatar';
import { BubbleProps } from '../Bubble';
import { ComposerProps } from '../Composer';
import { InputToolbarProps } from '../InputToolbar';
import { MessageProps } from '../Message';
import { AnimatedList, MessageContainerProps } from '../MessageContainer';
import { MessageImageProps } from '../MessageImage';
import { MessageTextProps } from '../MessageText';
import { QuickRepliesProps } from '../QuickReplies';
import { SendProps } from '../Send';
import { SystemMessageProps } from '../SystemMessage';
import { TimeProps } from '../Time';
import { IMessage, LeftRightStyle, MessageAudioProps, MessageVideoProps, User } from '../types';
export interface GiftedChatProps<TMessage extends IMessage> extends Partial<MessageContainerProps<TMessage>> {
    messageContainerRef?: RefObject<AnimatedList<TMessage>>;
    textInputRef?: RefObject<TextInput>;
    renderUsernameOnMessage?: boolean;
    messagesContainerStyle?: StyleProp<ViewStyle>;
    text?: string;
    initialText?: string;
    user?: User;
    locale?: string;
    timeFormat?: string;
    dateFormat?: string;
    dateFormatCalendar?: object;
    isKeyboardInternallyHandled?: boolean;
    showUserAvatar?: boolean;
    showAvatarForEveryMessage?: boolean;
    renderAvatarOnTop?: boolean;
    imageProps?: MessageImageProps<TMessage>;
    keyboardBottomOffset?: number;
    focusOnInputWhenOpeningKeyboard?: boolean;
    minInputToolbarHeight?: number;
    textInputProps?: Partial<React.ComponentProps<typeof TextInput>>;
    alwaysShowSend?: boolean;
    imageStyle?: StyleProp<ViewStyle>;
    minComposerHeight?: number;
    maxComposerHeight?: number;
    actions?: Array<{
        title: string;
        action: () => void;
    }>;
    actionSheetOptionTintColor?: string;
    quickReplyStyle?: StyleProp<ViewStyle>;
    quickReplyTextStyle?: StyleProp<TextStyle>;
    quickReplyContainerStyle?: StyleProp<ViewStyle>;
    isCustomViewBottom?: boolean;
    timeTextStyle?: LeftRightStyle<TextStyle>;
    actionSheet?(): {
        showActionSheetWithOptions: (options: ActionSheetOptions, callback: (buttonIndex: number) => void | Promise<void>) => void;
    };
    onPressAvatar?(user: User): void;
    onLongPressAvatar?(user: User): void;
    messageIdGenerator?(message?: TMessage): string;
    onSend?(messages: TMessage[]): void;
    renderLoading?(): React.ReactNode;
    renderAvatar?: null | ((props: AvatarProps<TMessage>) => React.ReactNode);
    renderBubble?(props: BubbleProps<TMessage>): React.ReactNode;
    renderSystemMessage?(props: SystemMessageProps<TMessage>): React.ReactNode;
    onPressMessage?(context: unknown, message: TMessage): void;
    onLongPressMessage?(context: unknown, message: TMessage): void;
    renderUsername?(user: User): React.ReactNode;
    renderMessageText?(messageText: MessageTextProps<TMessage>): React.ReactNode;
    renderMessageImage?(props: MessageImageProps<TMessage>): React.ReactNode;
    renderMessageVideo?(props: MessageVideoProps<TMessage>): React.ReactNode;
    renderMessageAudio?(props: MessageAudioProps<TMessage>): React.ReactNode;
    renderCustomView?(props: BubbleProps<TMessage>): React.ReactNode;
    renderTime?(props: TimeProps<TMessage>): React.ReactNode;
    renderChatFooter?(): React.ReactNode;
    renderInputToolbar?: React.ComponentType<InputToolbarProps<TMessage>> | React.ReactElement | ((props: InputToolbarProps<TMessage>) => React.ReactNode) | null;
    renderComposer?(props: ComposerProps): React.ReactNode;
    renderActions?(props: ActionsProps): React.ReactNode;
    renderSend?(props: SendProps<TMessage>): React.ReactNode;
    renderAccessory?(props: InputToolbarProps<TMessage>): React.ReactNode;
    onPressActionButton?(): void;
    onInputTextChanged?(text: string): void;
    messageTextProps?: Partial<MessageTextProps<TMessage>>;
    matchers?: MessageTextProps<TMessage>['matchers'];
    renderQuickReplies?(quickReplies: QuickRepliesProps<TMessage>): React.ReactNode;
    renderQuickReplySend?(): React.ReactNode;
    shouldUpdateMessage?(props: MessageProps<TMessage>, nextProps: MessageProps<TMessage>): boolean;
}
